config/routes.rb
Rails.application.routes.draw do
  resources :financial_statements do
    collection do
      post "scrape"
    end
  end

  root to: 'financial_statements#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :financial_statements
end

app/models/financial_statement.rb
class FinancialStatement < ApplicationRecord
  belongs_to :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/financial_statements_controller.rb
class FinancialStatementsController < ApplicationController
  before_action :set_financial_statement, only: [:show, :edit, :update, :destroy]

  # POST /financial_statements
  def scrape
    return if params[:symbol].blank?

    ScrapeYahooJob.perform_later(params[:symbol])

    render plain: "Job submitted"
  end

  # GET /financial_statements
  # GET /financial_statements.json
  def index
    @financial_statements = FinancialStatement.all
  end

  # GET /financial_statements/1
  # GET /financial_statements/1.json
  def show
    render json: @financial_statement
  end

  # GET /financial_statements/new
  def new
    @financial_statement = FinancialStatement.new
  end

  # GET /financial_statements/1/edit
  def edit
  end

  # POST /financial_statements
  # POST /financial_statements.json
  def create
    @financial_statement = FinancialStatement.new(financial_statement_params)

    respond_to do |format|
      if @financial_statement.save
        format.html { redirect_to @financial_statement, notice: 'Financial statement was successfully created.' }
        format.json { render :show, status: :created, location: @financial_statement }
      else
        format.html { render :new }
        format.json { render json: @financial_statement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /financial_statements/1
  # PATCH/PUT /financial_statements/1.json
  def update
    respond_to do |format|
      if @financial_statement.update(financial_statement_params)
        format.html { redirect_to @financial_statement, notice: 'Financial statement was successfully updated.' }
        format.json { render :show, status: :ok, location: @financial_statement }
      else
        format.html { render :edit }
        format.json { render json: @financial_statement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /financial_statements/1
  # DELETE /financial_statements/1.json
  def destroy
    @financial_statement.destroy
    respond_to do |format|
      format.html { redirect_to financial_statements_url, notice: 'Financial statement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_financial_statement
      @financial_statement = FinancialStatement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def financial_statement_params
      params.require(:financial_statement).permit(:symbol, :name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/financial_statements_helper.rb
module FinancialStatementsHelper
end

app/views/financial_statements/_form.html.erb
<%= form_with(model: financial_statement, local: true) do |form| %>
  <% if financial_statement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(financial_statement.errors.count, "error") %> prohibited this financial_statement from being saved:</h2>

      <ul>
      <% financial_statement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :symbol %>
    <%= form.text_field :symbol, id: :financial_statement_symbol %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :financial_statement_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :financial_statement_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/financial_statements/_scrape.html.erb
<form action="/financial_statements/scrape" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <label>Company Symbol (eg. VTI)</label>
  <input type="text" name="symbol">
  <button>Scrape</button>
</form>

app/views/financial_statements/edit.html.erb
<h1>Editing Financial Statement</h1>

<%= render 'form', financial_statement: @financial_statement %>

<%= link_to 'Show', @financial_statement %> |
<%= link_to 'Back', financial_statements_path %>

app/views/financial_statements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Financial Statements</h1>

<table>
  <thead>
    <tr>
      <th>Symbol</th>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @financial_statements.each do |financial_statement| %>
      <tr>
        <td><%= financial_statement.symbol %></td>
        <td><%= financial_statement.name %></td>
        <td><%= financial_statement.price %></td>
        <td><%= link_to 'Show', financial_statement %></td>
        <td><%= link_to 'Edit', edit_financial_statement_path(financial_statement) %></td>
        <td><%= link_to 'Destroy', financial_statement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Financial Statement', new_financial_statement_path %>

app/views/financial_statements/new.html.erb
<h1>New Financial Statement</h1>

<%= render 'scrape', financial_statement: @financial_statement %>

<%= link_to 'Back', financial_statements_path %>

app/views/financial_statements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Symbol:</strong>
  <%= @financial_statement.symbol %>
</p>

<p>
  <strong>Name:</strong>
  <%= @financial_statement.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @financial_statement.price %>
</p>

<%= link_to 'Edit', edit_financial_statement_path(@financial_statement) %> |
<%= link_to 'Back', financial_statements_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scraper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all'  %>
    <%= javascript_include_tag 'application'  %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>